/**
 * Template métier — Visite technique PAC Air/Air (climatisation réversible).
 * 6 étapes.
 */
import type { VisitTemplate } from "../types";

export const PAC_AIR_AIR_TEMPLATE: VisitTemplate = {
  type: "pac_air_air",
  label: "PAC Air/Air",
  chantierType: "Climatisation / PAC Air-Air",
  tagline: "Pièces à traiter, groupe extérieur, liaisons frigorifiques",
  photoCategories: [
    "Pièces",
    "Unités intérieures",
    "Groupe extérieur",
    "Liaisons",
    "Condensats",
    "Électricité",
    "Contraintes",
  ],
  sections: [
    {
      key: "configuration",
      title: "Configuration de l'installation",
      short: "Config",
      description: "Type de système et nombre d'unités à installer.",
      fields: [
        {
          key: "batiment_type",
          label: "Type de bâtiment",
          type: "select",
          required: true,
          options: [
            { value: "maison_individuelle", label: "Maison individuelle" },
            { value: "appartement", label: "Appartement" },
            { value: "local_pro", label: "Local professionnel" },
          ],
        },
        {
          key: "copropriete",
          label: "Copropriété (accord requis)",
          type: "boolean",
          help: "L'unité extérieure en façade nécessite souvent une autorisation.",
        },
        {
          key: "systeme",
          label: "Système retenu",
          type: "select",
          required: true,
          options: [
            { value: "monosplit", label: "Monosplit (1 unité intérieure)" },
            { value: "multisplit", label: "Multisplit (2 à 5 unités)" },
            { value: "gainable", label: "Gainable" },
            { value: "console", label: "Console / plafonnier" },
          ],
        },
        {
          key: "nb_unites",
          label: "Nombre d'unités intérieures",
          type: "number",
          required: true,
          min: 1,
          max: 5,
          help: "Un bloc de saisie sera créé pour chaque unité.",
        },
        { key: "isolation_niveau", label: "Niveau d'isolation", type: "select", required: true, options: [
          { value: "bonne", label: "Bonne (récente / rénovée)" },
          { value: "moyenne", label: "Moyenne" },
          { value: "faible", label: "Faible (non isolée)" },
        ] },
        { key: "chauffage_actuel", label: "Chauffage actuel", type: "text", placeholder: "Convecteurs électriques, insert bois…" },
        { key: "usage", label: "Usage principal attendu", type: "select", options: [
          { value: "chaud_froid", label: "Chaud et froid" },
          { value: "froid", label: "Rafraîchissement uniquement" },
          { value: "chaud", label: "Chauffage uniquement" },
        ] },
        { key: "config_notes", label: "Observations", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_facade", label: "Façade du bâtiment", category: "Groupe extérieur", required: true },
        { key: "photo_plan", label: "Plan ou croquis du logement", instruction: "Photo d'un plan papier si disponible.", category: "Pièces" },
      ],
    },
    {
      key: "pieces",
      title: "Pièces à traiter",
      short: "Pièces",
      description: "Une fiche par unité intérieure à poser.",
      repeat: { countField: "nb_unites", itemLabel: "Unité intérieure", min: 1, max: 5 },
      fields: [
        {
          key: "piece_nom",
          label: "Pièce",
          type: "select",
          required: true,
          options: [
            { value: "sejour", label: "Séjour / salon" },
            { value: "cuisine", label: "Cuisine" },
            { value: "chambre", label: "Chambre" },
            { value: "bureau", label: "Bureau" },
            { value: "sous_sol", label: "Sous-sol / garage" },
            { value: "commerce", label: "Local commercial" },
            { value: "autre", label: "Autre" },
          ],
        },
        { key: "piece_etage", label: "Étage", type: "select", required: true, options: [
          { value: "rdc", label: "Rez-de-chaussée" },
          { value: "etage1", label: "1er étage" },
          { value: "etage2", label: "2e étage et plus" },
          { value: "sous_sol", label: "Sous-sol" },
          { value: "combles", label: "Combles" },
        ] },
        { key: "piece_surface", label: "Surface", type: "number", unit: "m²", required: true, min: 0, max: 500, step: 0.5 },
        { key: "piece_hauteur", label: "Hauteur sous plafond", type: "number", unit: "m", required: true, min: 1.8, max: 8, step: 0.05 },
        { key: "piece_exposition", label: "Exposition", type: "select", options: [
          { value: "nord", label: "Nord" },
          { value: "est", label: "Est" },
          { value: "sud", label: "Sud" },
          { value: "ouest", label: "Ouest" },
        ] },
        { key: "piece_vitrage", label: "Surface vitrée estimée", type: "number", unit: "m²", min: 0, max: 100, step: 0.5 },
        {
          key: "ui_type",
          label: "Type d'unité intérieure",
          type: "select",
          required: true,
          options: [
            { value: "murale_haute", label: "Murale haute" },
            { value: "console", label: "Console basse" },
            { value: "cassette", label: "Cassette plafond" },
            { value: "gainable", label: "Gainable" },
          ],
        },
        { key: "ui_emplacement", label: "Emplacement précis de l'unité", type: "text", required: true, placeholder: "Mur nord, au-dessus de la porte" },
        { key: "ui_hauteur_pose", label: "Hauteur de pose prévue", type: "number", unit: "m", min: 0, max: 5, step: 0.05 },
        { key: "ui_support_nature", label: "Nature du mur support", type: "select", required: true, options: [
          { value: "beton", label: "Béton" },
          { value: "brique", label: "Brique / parpaing" },
          { value: "placo", label: "Placo sur ossature" },
          { value: "bois", label: "Bois" },
          { value: "pierre", label: "Pierre" },
        ] },
        { key: "piece_notes", label: "Observations sur la pièce", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_piece", label: "Vue générale de la pièce", instruction: "Depuis l'angle opposé au mur d'implantation.", category: "Pièces", required: true },
        { key: "photo_mur_ui", label: "Mur d'implantation de l'unité", instruction: "Cadrez le mur entier, du sol au plafond.", category: "Unités intérieures", required: true },
        { key: "photo_piece_contrainte", label: "Contrainte dans la pièce", instruction: "Meuble, poutre, conduit…", category: "Pièces", multiple: true },
      ],
    },
    {
      key: "groupe_exterieur",
      title: "Groupe extérieur",
      short: "Groupe ext.",
      description: "Emplacement, support et évacuation des condensats.",
      fields: [
        {
          key: "ue_emplacement",
          label: "Emplacement du groupe",
          type: "select",
          required: true,
          options: [
            { value: "sol", label: "Au sol" },
            { value: "facade", label: "En façade (console murale)" },
            { value: "balcon", label: "Balcon / terrasse" },
            { value: "toiture", label: "En toiture" },
            { value: "local_technique", label: "Local technique ventilé" },
          ],
        },
        { key: "ue_support", label: "Support à prévoir", type: "select", required: true, options: [
          { value: "plots_beton", label: "Plots béton" },
          { value: "console_murale", label: "Console murale" },
          { value: "chassis", label: "Châssis / rail" },
          { value: "existant", label: "Support existant réutilisable" },
        ] },
        { key: "ue_hauteur_travail", label: "Hauteur de travail", type: "number", unit: "m", min: 0, max: 20, step: 0.1 },
        { key: "ue_degagement", label: "Dégagement disponible devant le groupe", type: "number", unit: "m", required: true, min: 0, max: 20, step: 0.1, help: "Minimum recommandé : 0,5 m." },
        { key: "ue_distance_voisin", label: "Distance à la limite voisine", type: "number", unit: "m", min: 0, max: 100, step: 0.5 },
        { key: "ue_nuisance_sonore", label: "Risque de nuisance sonore", type: "select", required: true, options: [
          { value: "faible", label: "Faible" },
          { value: "modere", label: "Modéré (chambre / voisin proche)" },
          { value: "eleve", label: "Élevé (à traiter)" },
        ] },
        { key: "ue_condensats", label: "Évacuation des condensats", type: "select", required: true, options: [
          { value: "gravitaire", label: "Gravitaire (écoulement libre)" },
          { value: "reseau_ep", label: "Raccordement réseau EP" },
          { value: "pompe_relevage", label: "Pompe de relevage" },
          { value: "a_definir", label: "À définir" },
        ] },
        { key: "ue_notes", label: "Observations groupe extérieur", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_ue_emplacement", label: "Emplacement du groupe extérieur", instruction: "Cadrez la zone avec le mur et le sol.", category: "Groupe extérieur", required: true },
        { key: "photo_ue_environnement", label: "Environnement du groupe", instruction: "Montrez les dégagements et le voisinage.", category: "Groupe extérieur", required: true },
        { key: "photo_condensats", label: "Point d'évacuation des condensats", category: "Condensats", required: true },
      ],
    },
    {
      key: "liaisons",
      title: "Liaisons frigorifiques",
      short: "Liaisons",
      description: "Un bloc par unité intérieure : parcours, longueur, percements.",
      repeat: { countField: "nb_unites", itemLabel: "Liaison", min: 1, max: 5 },
      fields: [
        { key: "liaison_longueur", label: "Longueur de liaison", type: "number", unit: "m", required: true, min: 0, max: 60, step: 0.5 },
        { key: "liaison_denivele", label: "Dénivelé", type: "number", unit: "m", required: true, min: 0, max: 40, step: 0.5 },
        {
          key: "liaison_passage",
          label: "Type de passage",
          type: "select",
          required: true,
          options: [
            { value: "apparent_interieur", label: "Apparent intérieur (goulotte)" },
            { value: "encastre", label: "Encastré / saignée" },
            { value: "combles", label: "Combles" },
            { value: "vide_sanitaire", label: "Vide sanitaire" },
            { value: "faux_plafond", label: "Faux plafond" },
            { value: "exterieur", label: "Extérieur (goulotte UV)" },
          ],
        },
        { key: "liaison_nb_percements", label: "Nombre de percements", type: "number", required: true, min: 0, max: 12 },
        { key: "liaison_paroi_nature", label: "Nature des parois à percer", type: "text", placeholder: "Béton 25 cm, double cloison brique…" },
        { key: "liaison_pompe_relevage", label: "Pompe de relevage nécessaire", type: "boolean", help: "Requise si l'écoulement gravitaire des condensats est impossible." },
        { key: "liaison_goulotte_ml", label: "Métrage de goulotte", type: "number", unit: "m", min: 0, max: 60, step: 0.5 },
        { key: "liaison_notes", label: "Observations liaison", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_liaison_parcours", label: "Parcours de la liaison", instruction: "Montrez le trajet unité → groupe.", category: "Liaisons", required: true, multiple: true },
        { key: "photo_liaison_percement", label: "Zone de percement", instruction: "Intérieur et extérieur si possible.", category: "Liaisons", required: true },
      ],
    },
    {
      key: "electricite",
      title: "Alimentation électrique",
      short: "Électricité",
      fields: [
        { key: "type_alimentation", label: "Type d'alimentation", type: "select", required: true, options: [
          { value: "monophase", label: "Monophasé" },
          { value: "triphase", label: "Triphasé" },
        ] },
        { key: "puissance_souscrite", label: "Puissance souscrite", type: "number", unit: "kVA", required: true, min: 0, max: 250 },
        { key: "tableau_etat", label: "État du tableau électrique", type: "select", required: true, options: [
          { value: "conforme", label: "Conforme et récent" },
          { value: "acceptable", label: "Acceptable" },
          { value: "vetuste", label: "Vétuste (mise à niveau)" },
        ] },
        { key: "tableau_place_dispo", label: "Modules libres au tableau", type: "number", min: 0, max: 60, required: true },
        { key: "ligne_dediee_existante", label: "Ligne dédiée existante", type: "boolean" },
        { key: "distance_tableau_ue", label: "Distance tableau → groupe extérieur", type: "number", unit: "m", required: true, min: 0, max: 200, step: 0.5 },
        { key: "terre_presente", label: "Mise à la terre présente", type: "select", required: true, options: [
          { value: "oui", label: "Oui" },
          { value: "non", label: "Non" },
          { value: "inconnu", label: "À vérifier" },
        ] },
        { key: "electricite_notes", label: "Observations électriques", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_tableau", label: "Tableau électrique ouvert", instruction: "Capot retiré, protections visibles.", category: "Électricité", required: true },
        { key: "photo_compteur", label: "Compteur / disjoncteur d'abonné", category: "Électricité", required: true },
      ],
    },
    {
      key: "contraintes",
      title: "Contraintes & points de vigilance",
      short: "Contraintes",
      kind: "constraints",
      fields: [
        { key: "contraintes_synthese", label: "Synthèse des contraintes", type: "textarea", wide: true },
        { key: "faisabilite", label: "Faisabilité technique", type: "select", required: true, options: [
          { value: "favorable", label: "Favorable" },
          { value: "favorable_reserves", label: "Favorable avec réserves" },
          { value: "a_etudier", label: "À étudier (bureau d'études)" },
          { value: "defavorable", label: "Défavorable" },
        ] },
      ],
      photos: [
        { key: "photo_contraintes", label: "Photos de contraintes", instruction: "Une photo par point de vigilance.", category: "Contraintes", multiple: true },
      ],
    },
    {
      key: "verification",
      title: "Vérification finale",
      short: "Vérification",
      kind: "review",
      fields: [],
      photos: [],
    },
  ],
};
