/**
 * Template métier — Visite technique PAC Air/Eau.
 * 8 étapes.
 */
import type { VisitTemplate } from "../types";

const OUI_NON = [
  { value: "oui", label: "Oui" },
  { value: "non", label: "Non" },
  { value: "inconnu", label: "À vérifier" },
];

export const PAC_AIR_EAU_TEMPLATE: VisitTemplate = {
  type: "pac_air_eau",
  label: "PAC Air/Eau",
  chantierType: "Pompe à chaleur Air-Eau",
  tagline: "Générateur existant, émetteurs, hydraulique et ECS",
  photoCategories: [
    "Installation existante",
    "Chaufferie",
    "Émetteurs",
    "Hydraulique",
    "ECS",
    "Unité extérieure",
    "Électricité",
    "Contraintes",
  ],
  sections: [
    {
      key: "existant",
      title: "Installation existante",
      short: "Existant",
      description: "Générateur en place et son état.",
      fields: [
        {
          key: "generateur_type",
          label: "Générateur actuel",
          type: "select",
          required: true,
          options: [
            { value: "chaudiere_gaz", label: "Chaudière gaz" },
            { value: "chaudiere_fioul", label: "Chaudière fioul" },
            { value: "chaudiere_bois", label: "Chaudière bois / granulés" },
            { value: "electrique", label: "Chauffage électrique" },
            { value: "pac_existante", label: "PAC existante" },
            { value: "aucun", label: "Aucun (neuf)" },
          ],
        },
        { key: "generateur_marque", label: "Marque / modèle", type: "text", placeholder: "Relevé sur la plaque signalétique" },
        { key: "generateur_puissance", label: "Puissance du générateur", type: "number", unit: "kW", min: 0, max: 500 },
        { key: "generateur_annee", label: "Année d'installation", type: "number", min: 1950, max: 2100 },
        { key: "generateur_etat", label: "État général", type: "select", required: true, options: [
          { value: "bon", label: "Bon" },
          { value: "moyen", label: "Moyen" },
          { value: "hors_service", label: "Hors service" },
        ] },
        { key: "depose_prevue", label: "Dépose de l'ancien générateur à prévoir", type: "boolean", required: false },
        { key: "cuve_fioul", label: "Cuve fioul à neutraliser", type: "select", options: OUI_NON, visibleIf: [{ field: "generateur_type", equals: "chaudiere_fioul" }] },
        { key: "conduit_fumee", label: "Devenir du conduit de fumée", type: "text", visibleIf: [{ field: "generateur_type", in: ["chaudiere_gaz", "chaudiere_fioul", "chaudiere_bois"] }] },
        { key: "existant_notes", label: "Observations", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_generateur", label: "Générateur existant", instruction: "Vue d'ensemble de la chaudière.", category: "Installation existante", required: true },
        { key: "photo_plaque", label: "Plaque signalétique", instruction: "Marque, modèle et puissance lisibles.", category: "Installation existante", required: true },
        { key: "photo_chaufferie", label: "Vue générale de la chaufferie", instruction: "Montrez les dégagements disponibles.", category: "Chaufferie", required: true },
        { key: "photo_cuve", label: "Cuve fioul", category: "Installation existante", visibleIf: [{ field: "generateur_type", equals: "chaudiere_fioul" }] },
      ],
    },
    {
      key: "emetteurs",
      title: "Émetteurs de chaleur",
      short: "Émetteurs",
      description: "Nature des émetteurs et température de fonctionnement.",
      fields: [
        {
          key: "emetteurs_type",
          label: "Type d'émetteurs",
          type: "multiselect",
          required: true,
          options: [
            { value: "radiateurs_fonte", label: "Radiateurs fonte" },
            { value: "radiateurs_acier", label: "Radiateurs acier / panneaux" },
            { value: "plancher_chauffant", label: "Plancher chauffant" },
            { value: "ventilo_convecteurs", label: "Ventilo-convecteurs" },
            { value: "mixte", label: "Mixte" },
          ],
        },
        { key: "nb_emetteurs", label: "Nombre total d'émetteurs", type: "number", required: true, min: 0, max: 100 },
        {
          key: "temperature_regime",
          label: "Régime de température estimé",
          type: "select",
          required: true,
          options: [
            { value: "bt", label: "Basse température (≤ 45 °C)" },
            { value: "mt", label: "Moyenne température (45-55 °C)" },
            { value: "ht", label: "Haute température (> 55 °C)" },
            { value: "inconnu", label: "À déterminer" },
          ],
        },
        { key: "emetteurs_surdimensionnes", label: "Émetteurs compatibles basse température", type: "select", required: true, options: OUI_NON },
        { key: "robinets_thermostatiques", label: "Robinets thermostatiques présents", type: "boolean" },
        { key: "nb_circuits", label: "Nombre de circuits de distribution", type: "number", required: true, min: 1, max: 10 },
        { key: "regulation_existante", label: "Régulation existante", type: "text", placeholder: "Thermostat d'ambiance, sonde extérieure…" },
        { key: "emetteurs_notes", label: "Observations émetteurs", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_emetteur_type", label: "Émetteur représentatif", instruction: "Photo d'un radiateur type avec sa robinetterie.", category: "Émetteurs", required: true },
        { key: "photo_emetteurs_autres", label: "Autres émetteurs", instruction: "Un cliché par typologie différente.", category: "Émetteurs", multiple: true },
        { key: "photo_collecteur", label: "Collecteur plancher chauffant", category: "Émetteurs", visibleIf: [{ field: "emetteurs_type", in: ["plancher_chauffant", "mixte"] }] },
      ],
    },
    {
      key: "logement",
      title: "Caractéristiques du logement",
      short: "Logement",
      fields: [
        { key: "surface_chauffee", label: "Surface chauffée", type: "number", unit: "m²", required: true, min: 0, max: 3000 },
        { key: "hauteur_plafond", label: "Hauteur sous plafond moyenne", type: "number", unit: "m", required: true, min: 1.8, max: 8, step: 0.05 },
        { key: "annee_construction", label: "Année de construction", type: "number", min: 1800, max: 2100, required: true },
        { key: "isolation_murs", label: "Isolation des murs", type: "select", required: true, options: [
          { value: "ite", label: "Isolation par l'extérieur" },
          { value: "iti", label: "Isolation par l'intérieur" },
          { value: "aucune", label: "Aucune" },
          { value: "inconnu", label: "À vérifier" },
        ] },
        { key: "isolation_combles", label: "Isolation des combles", type: "select", required: true, options: [
          { value: "bonne", label: "Bonne (≥ 30 cm)" },
          { value: "partielle", label: "Partielle" },
          { value: "aucune", label: "Aucune" },
        ] },
        { key: "menuiseries", label: "Menuiseries", type: "select", required: true, options: [
          { value: "double_recent", label: "Double vitrage récent" },
          { value: "double_ancien", label: "Double vitrage ancien" },
          { value: "simple", label: "Simple vitrage" },
          { value: "mixte", label: "Mixte" },
        ] },
        { key: "nb_occupants", label: "Nombre d'occupants", type: "number", min: 1, max: 30, required: true },
        { key: "conso_actuelle", label: "Consommation actuelle déclarée", type: "text", placeholder: "1 800 L de fioul / an, 15 000 kWh gaz…" },
        { key: "logement_notes", label: "Observations", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_facade", label: "Façade du logement", category: "Installation existante", required: true },
        { key: "photo_combles_isolation", label: "Isolation des combles", category: "Installation existante" },
      ],
    },
    {
      key: "emplacement_pac",
      title: "Emplacement de la PAC",
      short: "Emplacement",
      description: "Unité extérieure et module hydraulique intérieur.",
      fields: [
        { key: "ue_emplacement", label: "Emplacement de l'unité extérieure", type: "select", required: true, options: [
          { value: "sol_facade", label: "Au sol le long de la façade" },
          { value: "sol_jardin", label: "Au sol déporté (jardin)" },
          { value: "terrasse", label: "Terrasse / balcon" },
          { value: "toiture", label: "Toiture" },
          { value: "local", label: "Local ouvert / carport" },
        ] },
        { key: "ue_support", label: "Support à prévoir", type: "select", required: true, options: [
          { value: "plots_beton", label: "Plots béton" },
          { value: "dalle", label: "Dalle à couler" },
          { value: "chassis", label: "Châssis anti-vibratile" },
          { value: "existant", label: "Support existant" },
        ] },
        { key: "ue_degagement", label: "Dégagement devant l'unité", type: "number", unit: "m", required: true, min: 0, max: 20, step: 0.1 },
        { key: "ue_distance_voisin", label: "Distance à la limite voisine", type: "number", unit: "m", min: 0, max: 100, step: 0.5 },
        { key: "ue_nuisance_sonore", label: "Risque de nuisance sonore", type: "select", required: true, options: [
          { value: "faible", label: "Faible" },
          { value: "modere", label: "Modéré" },
          { value: "eleve", label: "Élevé (à traiter)" },
        ] },
        { key: "ue_evacuation_condensats", label: "Évacuation des condensats prévue", type: "select", required: true, options: [
          { value: "puisard", label: "Puisard / lit de gravier" },
          { value: "reseau_ep", label: "Réseau eaux pluviales" },
          { value: "a_definir", label: "À définir" },
        ] },
        { key: "module_interieur_emplacement", label: "Emplacement du module intérieur", type: "text", required: true, placeholder: "Ancienne chaufferie, garage…" },
        { key: "distance_ue_module", label: "Distance unité extérieure → module", type: "number", unit: "m", required: true, min: 0, max: 60, step: 0.5 },
        { key: "passage_liaisons", label: "Passage des liaisons", type: "select", required: true, options: [
          { value: "traversee_murale", label: "Traversée murale directe" },
          { value: "vide_sanitaire", label: "Vide sanitaire" },
          { value: "tranchee", label: "Tranchée enterrée" },
          { value: "apparent", label: "Apparent extérieur" },
        ] },
        { key: "tranchee_ml", label: "Métrage de tranchée", type: "number", unit: "m", min: 0, max: 200, visibleIf: [{ field: "passage_liaisons", equals: "tranchee" }] },
        { key: "emplacement_notes", label: "Observations", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_ue_emplacement", label: "Emplacement de l'unité extérieure", instruction: "Cadrez la zone avec le mur et le sol.", category: "Unité extérieure", required: true },
        { key: "photo_ue_environnement", label: "Environnement et dégagements", category: "Unité extérieure", required: true },
        { key: "photo_module_interieur", label: "Emplacement du module intérieur", category: "Chaufferie", required: true },
        { key: "photo_traversee", label: "Zone de traversée / tranchée", category: "Unité extérieure" },
      ],
    },
    {
      key: "hydraulique",
      title: "Réseau hydraulique",
      short: "Hydraulique",
      fields: [
        { key: "diametre_depart", label: "Diamètre du départ chauffage", type: "text", required: true, placeholder: "DN25, 26/34, cuivre 22…" },
        { key: "materiau_reseau", label: "Matériau du réseau", type: "select", required: true, options: [
          { value: "cuivre", label: "Cuivre" },
          { value: "acier", label: "Acier noir" },
          { value: "per", label: "PER / multicouche" },
          { value: "mixte", label: "Mixte" },
        ] },
        { key: "reseau_etat", label: "État du réseau", type: "select", required: true, options: [
          { value: "bon", label: "Bon" },
          { value: "moyen", label: "Moyen" },
          { value: "corrode", label: "Corrodé / embouage" },
        ] },
        { key: "ballon_tampon", label: "Ballon tampon nécessaire", type: "boolean", help: "Souvent requis si volume d'eau insuffisant ou robinets thermostatiques généralisés." },
        { key: "ballon_tampon_volume", label: "Volume de ballon tampon envisagé", type: "number", unit: "L", min: 0, max: 1000, visibleIf: [{ field: "ballon_tampon", truthy: true }] },
        { key: "desembouage", label: "Désembouage à prévoir", type: "select", required: true, options: OUI_NON },
        { key: "vase_expansion", label: "Vase d'expansion présent", type: "select", options: OUI_NON },
        { key: "circulateur", label: "Circulateur à remplacer", type: "boolean" },
        { key: "vannes_isolement", label: "Vannes d'isolement présentes", type: "boolean" },
        { key: "hydraulique_notes", label: "Observations hydrauliques", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_departs", label: "Départs et retours chauffage", instruction: "Cadrez la nourrice / les piquages.", category: "Hydraulique", required: true },
        { key: "photo_circulateur", label: "Circulateur et vannes", category: "Hydraulique", required: true },
        { key: "photo_vase", label: "Vase d'expansion", category: "Hydraulique" },
      ],
    },
    {
      key: "ecs",
      title: "Eau chaude sanitaire",
      short: "ECS",
      description: "À renseigner si la PAC assure aussi l'ECS.",
      fields: [
        { key: "ecs_incluse", label: "ECS assurée par la PAC", type: "boolean", required: false },
        { key: "ecs_production_actuelle", label: "Production d'ECS actuelle", type: "select", options: [
          { value: "chaudiere", label: "Par la chaudière" },
          { value: "cumulus", label: "Cumulus électrique" },
          { value: "ballon_thermo", label: "Ballon thermodynamique" },
          { value: "instantane", label: "Instantané" },
        ], visibleIf: [{ field: "ecs_incluse", truthy: true }] },
        { key: "ecs_volume", label: "Volume de ballon souhaité", type: "number", unit: "L", min: 0, max: 1000, visibleIf: [{ field: "ecs_incluse", truthy: true }] },
        { key: "ecs_emplacement", label: "Emplacement du ballon", type: "text", visibleIf: [{ field: "ecs_incluse", truthy: true }] },
        { key: "ecs_hauteur_dispo", label: "Hauteur disponible", type: "number", unit: "m", min: 0, max: 5, step: 0.05, visibleIf: [{ field: "ecs_incluse", truthy: true }] },
        { key: "ecs_evacuation", label: "Évacuation à proximité", type: "boolean", visibleIf: [{ field: "ecs_incluse", truthy: true }] },
        { key: "ecs_notes", label: "Observations ECS", type: "textarea", wide: true, visibleIf: [{ field: "ecs_incluse", truthy: true }] },
      ],
      photos: [
        { key: "photo_ecs_existant", label: "Production d'ECS actuelle", category: "ECS", visibleIf: [{ field: "ecs_incluse", truthy: true }] },
        { key: "photo_ecs_emplacement", label: "Emplacement du futur ballon", instruction: "Montrez la hauteur disponible.", category: "ECS", visibleIf: [{ field: "ecs_incluse", truthy: true }] },
      ],
    },
    {
      key: "electricite",
      title: "Alimentation électrique",
      short: "Électricité",
      fields: [
        { key: "type_alimentation", label: "Type d'alimentation", type: "select", required: true, options: [
          { value: "monophase", label: "Monophasé" },
          { value: "triphase", label: "Triphasé" },
        ] },
        { key: "puissance_souscrite", label: "Puissance souscrite", type: "number", unit: "kVA", required: true, min: 0, max: 250 },
        { key: "augmentation_puissance", label: "Augmentation de puissance à prévoir", type: "select", required: true, options: OUI_NON },
        { key: "tableau_etat", label: "État du tableau électrique", type: "select", required: true, options: [
          { value: "conforme", label: "Conforme et récent" },
          { value: "acceptable", label: "Acceptable" },
          { value: "vetuste", label: "Vétuste (mise à niveau)" },
        ] },
        { key: "tableau_place_dispo", label: "Modules libres au tableau", type: "number", required: true, min: 0, max: 60 },
        { key: "distance_tableau_pac", label: "Distance tableau → PAC", type: "number", unit: "m", required: true, min: 0, max: 200, step: 0.5 },
        { key: "terre_presente", label: "Mise à la terre présente", type: "select", required: true, options: OUI_NON },
        { key: "electricite_notes", label: "Observations électriques", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_tableau", label: "Tableau électrique ouvert", instruction: "Capot retiré, protections visibles.", category: "Électricité", required: true },
        { key: "photo_compteur", label: "Compteur / disjoncteur d'abonné", instruction: "Calibre et PDL lisibles.", category: "Électricité", required: true },
      ],
    },
    {
      key: "contraintes",
      title: "Contraintes & points de vigilance",
      short: "Contraintes",
      kind: "constraints",
      fields: [
        { key: "contraintes_synthese", label: "Synthèse des contraintes", type: "textarea", wide: true },
        { key: "faisabilite", label: "Faisabilité technique", type: "select", required: true, options: [
          { value: "favorable", label: "Favorable" },
          { value: "favorable_reserves", label: "Favorable avec réserves" },
          { value: "a_etudier", label: "À étudier (bureau d'études)" },
          { value: "defavorable", label: "Défavorable" },
        ] },
      ],
      photos: [
        { key: "photo_contraintes", label: "Photos de contraintes", instruction: "Une photo par point de vigilance.", category: "Contraintes", multiple: true },
      ],
    },
    {
      key: "verification",
      title: "Vérification finale",
      short: "Vérification",
      kind: "review",
      fields: [],
      photos: [],
    },
  ],
};
