/**
 * Template métier — Visite technique Photovoltaïque.
 * 7 étapes. Les clés de champs ne doivent jamais être renommées (données historiques).
 */
import type { VisitTemplate } from "../types";

const OUI_NON = [
  { value: "oui", label: "Oui" },
  { value: "non", label: "Non" },
  { value: "inconnu", label: "À vérifier" },
];

export const PHOTOVOLTAIQUE_TEMPLATE: VisitTemplate = {
  type: "photovoltaique",
  label: "Photovoltaïque",
  chantierType: "Photovoltaïque",
  tagline: "Toiture, accès, raccordement électrique et cheminements",
  photoCategories: [
    "Bâtiment",
    "Toiture",
    "Accès & levage",
    "Électricité",
    "Onduleur & batterie",
    "Cheminements",
    "Contraintes",
  ],
  sections: [
    {
      key: "general",
      title: "Informations générales",
      short: "Général",
      description: "Contexte du site et de l'occupant.",
      fields: [
        {
          key: "batiment_type",
          label: "Type de bâtiment",
          type: "select",
          required: true,
          options: [
            { value: "maison_individuelle", label: "Maison individuelle" },
            { value: "maison_mitoyenne", label: "Maison mitoyenne" },
            { value: "immeuble", label: "Immeuble" },
            { value: "batiment_agricole", label: "Bâtiment agricole" },
            { value: "batiment_industriel", label: "Bâtiment industriel / tertiaire" },
            { value: "hangar", label: "Hangar / dépendance" },
          ],
        },
        { key: "annee_construction", label: "Année de construction", type: "number", min: 1800, max: 2100, placeholder: "1998" },
        {
          key: "occupation",
          label: "Occupation du logement",
          type: "select",
          options: [
            { value: "proprietaire", label: "Propriétaire occupant" },
            { value: "locataire", label: "Locataire" },
            { value: "vacant", label: "Vacant" },
          ],
        },
        { key: "surface_habitable", label: "Surface habitable", type: "number", unit: "m²", min: 0, max: 5000 },
        { key: "nb_niveaux", label: "Nombre de niveaux", type: "number", min: 1, max: 12, required: true },
        {
          key: "zone_protegee",
          label: "Zone protégée / ABF / copropriété",
          type: "select",
          options: OUI_NON,
          help: "Un avis architecte ou copropriété peut être obligatoire.",
        },
        { key: "consommation_annuelle", label: "Consommation annuelle déclarée", type: "number", unit: "kWh" },
        { key: "objectif_client", label: "Objectif du client", type: "textarea", wide: true, placeholder: "Autoconsommation, revente de surplus, borne de recharge à venir…" },
      ],
      photos: [
        { key: "photo_facade", label: "Façade principale", instruction: "Reculez pour cadrer tout le bâtiment.", category: "Bâtiment", required: true },
        { key: "photo_vue_ensemble", label: "Vue d'ensemble du site", instruction: "Montrez l'environnement immédiat (voisinage, arbres).", category: "Bâtiment", required: true, multiple: true },
        { key: "photo_compteur_exterieur", label: "Coffret / compteur extérieur", instruction: "Photo du coffret côté rue s'il existe.", category: "Bâtiment" },
      ],
    },
    {
      key: "toiture",
      title: "Toiture",
      short: "Toiture",
      description: "Nature, état et géométrie de la couverture.",
      fields: [
        {
          key: "couverture_type",
          label: "Type de couverture",
          type: "select",
          required: true,
          options: [
            { value: "tuiles_mecaniques", label: "Tuiles mécaniques" },
            { value: "tuiles_canal", label: "Tuiles canal" },
            { value: "tuiles_plates", label: "Tuiles plates" },
            { value: "ardoises", label: "Ardoises" },
            { value: "bac_acier", label: "Bac acier" },
            { value: "fibro_ciment", label: "Fibro-ciment" },
            { value: "toit_terrasse", label: "Toit terrasse / étanchéité" },
            { value: "autre", label: "Autre" },
          ],
        },
        {
          key: "couverture_etat",
          label: "État de la couverture",
          type: "select",
          required: true,
          options: [
            { value: "bon", label: "Bon" },
            { value: "moyen", label: "Moyen" },
            { value: "degrade", label: "Dégradé (reprise nécessaire)" },
          ],
        },
        {
          key: "amiante_suspecte",
          label: "Présence d'amiante suspectée",
          type: "select",
          options: OUI_NON,
          help: "Fibro-ciment avant 1997 : diagnostic obligatoire avant intervention.",
          visibleIf: [{ field: "couverture_type", in: ["fibro_ciment", "autre"] }],
        },
        {
          key: "charpente_type",
          label: "Type de charpente",
          type: "select",
          required: true,
          options: [
            { value: "traditionnelle", label: "Traditionnelle" },
            { value: "fermette", label: "Fermette industrielle" },
            { value: "metallique", label: "Métallique" },
            { value: "beton", label: "Béton" },
          ],
        },
        { key: "charpente_etat", label: "Observations charpente", type: "textarea", wide: true, placeholder: "Section des chevrons, entraxe, humidité, déformation…" },
        { key: "combles_accessibles", label: "Combles accessibles", type: "boolean" },
        { key: "nb_pans", label: "Nombre de pans exploitables", type: "number", required: true, min: 1, max: 6, help: "Un bloc de saisie sera créé pour chaque pan." },
      ],
      photos: [
        { key: "photo_toiture_ensemble", label: "Toiture vue d'ensemble", instruction: "Cadrez l'intégralité de la toiture.", category: "Toiture", required: true, multiple: true },
        { key: "photo_couverture_detail", label: "Détail de la couverture", instruction: "Gros plan sur les tuiles / le bac pour identifier le modèle.", category: "Toiture", required: true },
        { key: "photo_charpente", label: "Charpente / sous-toiture", instruction: "Depuis les combles si accessibles.", category: "Toiture", required: true },
        { key: "photo_faitage", label: "Faîtage et rives", category: "Toiture" },
      ],
    },
    {
      key: "pans",
      title: "Pans de toiture",
      short: "Pans",
      description: "Caractéristiques de chaque pan retenu pour l'implantation.",
      repeat: { countField: "nb_pans", itemLabel: "Pan", min: 1, max: 6 },
      fields: [
        {
          key: "pan_orientation",
          label: "Orientation",
          type: "select",
          required: true,
          options: [
            { value: "sud", label: "Sud" },
            { value: "sud_est", label: "Sud-Est" },
            { value: "sud_ouest", label: "Sud-Ouest" },
            { value: "est", label: "Est" },
            { value: "ouest", label: "Ouest" },
            { value: "nord_est", label: "Nord-Est" },
            { value: "nord_ouest", label: "Nord-Ouest" },
            { value: "nord", label: "Nord" },
          ],
        },
        { key: "pan_inclinaison", label: "Inclinaison", type: "number", unit: "°", required: true, min: 0, max: 90 },
        { key: "pan_longueur", label: "Longueur (rampant)", type: "number", unit: "m", required: true, min: 0, max: 200, step: 0.1 },
        { key: "pan_largeur", label: "Largeur (égout → faîtage)", type: "number", unit: "m", required: true, min: 0, max: 200, step: 0.1 },
        { key: "pan_hauteur_gouttiere", label: "Hauteur de gouttière", type: "number", unit: "m", required: true, min: 0, max: 60, step: 0.1 },
        {
          key: "pan_obstacles",
          label: "Obstacles présents",
          type: "multiselect",
          options: [
            { value: "cheminee", label: "Cheminée" },
            { value: "velux", label: "Fenêtre de toit / Velux" },
            { value: "chien_assis", label: "Chien-assis / lucarne" },
            { value: "antenne", label: "Antenne / parabole" },
            { value: "vmc", label: "Sortie VMC" },
            { value: "panneaux_existants", label: "Panneaux existants" },
            { value: "aucun", label: "Aucun" },
          ],
        },
        {
          key: "pan_masques",
          label: "Masques / ombrages",
          type: "multiselect",
          options: [
            { value: "arbres", label: "Arbres" },
            { value: "batiment_voisin", label: "Bâtiment voisin" },
            { value: "relief", label: "Relief" },
            { value: "poteau", label: "Poteau / ligne" },
            { value: "aucun", label: "Aucun" },
          ],
        },
        { key: "pan_surface_utile", label: "Surface utile estimée", type: "number", unit: "m²", min: 0, max: 5000, step: 0.5 },
        { key: "pan_notes", label: "Observations sur le pan", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_pan", label: "Vue du pan", instruction: "Cadrez le pan entier, de l'égout au faîtage.", category: "Toiture", required: true, multiple: true },
        { key: "photo_pan_obstacles", label: "Obstacles du pan", instruction: "Une photo par obstacle gênant l'implantation.", category: "Toiture", multiple: true },
      ],
    },
    {
      key: "acces",
      title: "Accès & levage",
      short: "Accès",
      description: "Conditions d'accès du camion, du matériel et des équipes.",
      fields: [
        {
          key: "acces_vehicule",
          label: "Accès véhicule utilitaire",
          type: "select",
          required: true,
          options: [
            { value: "facile", label: "Facile (devant le chantier)" },
            { value: "moyen", label: "Moyen (portage < 30 m)" },
            { value: "difficile", label: "Difficile (portage > 30 m)" },
            { value: "impossible", label: "Impossible" },
          ],
        },
        { key: "largeur_passage", label: "Largeur de passage la plus étroite", type: "number", unit: "m", min: 0, max: 20, step: 0.1 },
        { key: "stationnement", label: "Stationnement possible", type: "select", required: true, options: [
          { value: "prive", label: "Sur terrain privé" },
          { value: "rue", label: "Dans la rue" },
          { value: "autorisation", label: "Autorisation de voirie nécessaire" },
          { value: "aucun", label: "Aucun" },
        ] },
        {
          key: "moyen_acces_toiture",
          label: "Moyen d'accès en toiture",
          type: "select",
          required: true,
          options: [
            { value: "echelle", label: "Échelle" },
            { value: "echafaudage", label: "Échafaudage" },
            { value: "nacelle", label: "Nacelle" },
            { value: "interieur", label: "Par l'intérieur (combles)" },
          ],
        },
        {
          key: "nacelle_zone_pose",
          label: "Zone de pose de la nacelle disponible",
          type: "boolean",
          visibleIf: [{ field: "moyen_acces_toiture", equals: "nacelle" }],
          help: "Vérifiez la portance du sol et les lignes aériennes.",
        },
        { key: "ligne_aerienne", label: "Ligne aérienne / obstacle en hauteur", type: "select", options: OUI_NON },
        { key: "zone_stockage", label: "Zone de stockage matériel sur site", type: "boolean" },
        { key: "acces_notes", label: "Observations accès", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_acces_rue", label: "Accès depuis la rue", instruction: "Montrez le chemin emprunté par le camion.", category: "Accès & levage", required: true },
        { key: "photo_zone_levage", label: "Zone de levage / échafaudage", instruction: "Cadrez la zone au pied du bâtiment.", category: "Accès & levage", required: true },
        { key: "photo_contrainte_acces", label: "Contrainte d'accès", instruction: "Passage étroit, dénivelé, portail…", category: "Accès & levage", multiple: true },
      ],
    },
    {
      key: "electricite",
      title: "Installation électrique",
      short: "Électricité",
      description: "Comptage, tableau, mise à la terre et matériel envisagé.",
      fields: [
        {
          key: "type_alimentation",
          label: "Type d'alimentation",
          type: "select",
          required: true,
          options: [
            { value: "monophase", label: "Monophasé" },
            { value: "triphase", label: "Triphasé" },
          ],
        },
        { key: "puissance_souscrite", label: "Puissance souscrite", type: "number", unit: "kVA", required: true, min: 0, max: 250 },
        {
          key: "compteur_type",
          label: "Type de compteur",
          type: "select",
          required: true,
          options: [
            { value: "linky", label: "Linky" },
            { value: "electronique", label: "Électronique" },
            { value: "electromecanique", label: "Électromécanique (à changer)" },
          ],
        },
        { key: "pdl", label: "Numéro de PDL / PRM", type: "text", placeholder: "14 chiffres", help: "Indispensable pour la demande de raccordement." },
        {
          key: "compteur_emplacement",
          label: "Emplacement du compteur",
          type: "select",
          required: true,
          options: [
            { value: "interieur", label: "Intérieur" },
            { value: "exterieur", label: "Extérieur (coffret)" },
            { value: "limite_propriete", label: "En limite de propriété" },
          ],
        },
        { key: "distance_compteur_onduleur", label: "Distance compteur → onduleur", type: "number", unit: "m", required: true, min: 0, max: 300, step: 0.5 },
        {
          key: "tableau_etat",
          label: "État du tableau électrique",
          type: "select",
          required: true,
          options: [
            { value: "conforme", label: "Conforme et récent" },
            { value: "acceptable", label: "Acceptable" },
            { value: "vetuste", label: "Vétuste (mise à niveau)" },
          ],
        },
        { key: "tableau_place_dispo", label: "Modules libres au tableau", type: "number", min: 0, max: 60 },
        { key: "terre_presente", label: "Mise à la terre présente", type: "select", required: true, options: OUI_NON },
        { key: "terre_valeur", label: "Valeur de terre mesurée", type: "number", unit: "Ω", min: 0, max: 1000, visibleIf: [{ field: "terre_presente", equals: "oui" }] },
        {
          key: "emplacement_onduleur",
          label: "Emplacement prévu de l'onduleur",
          type: "select",
          required: true,
          options: [
            { value: "garage", label: "Garage" },
            { value: "cellier", label: "Cellier / buanderie" },
            { value: "combles", label: "Combles" },
            { value: "cave", label: "Cave / sous-sol" },
            { value: "exterieur_abrite", label: "Extérieur abrité" },
            { value: "autre", label: "Autre" },
          ],
        },
        { key: "onduleur_ventilation", label: "Local ventilé / hors gel", type: "boolean" },
        { key: "batterie_prevue", label: "Batterie de stockage prévue", type: "boolean" },
        { key: "batterie_capacite", label: "Capacité de batterie envisagée", type: "number", unit: "kWh", min: 0, max: 200, visibleIf: [{ field: "batterie_prevue", truthy: true }] },
        { key: "batterie_emplacement", label: "Emplacement de la batterie", type: "text", visibleIf: [{ field: "batterie_prevue", truthy: true }] },
        { key: "borne_recharge", label: "Borne de recharge existante ou prévue", type: "boolean" },
        { key: "electricite_notes", label: "Observations électriques", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_compteur", label: "Compteur", instruction: "Le numéro de PDL doit être lisible.", category: "Électricité", required: true },
        { key: "photo_disjoncteur", label: "Disjoncteur d'abonné", instruction: "Calibre visible.", category: "Électricité", required: true },
        { key: "photo_tableau", label: "Tableau électrique ouvert", instruction: "Capot retiré, protections visibles.", category: "Électricité", required: true },
        { key: "photo_terre", label: "Barrette / piquet de terre", category: "Électricité" },
        { key: "photo_emplacement_onduleur", label: "Emplacement de l'onduleur", instruction: "Cadrez le mur support et son environnement.", category: "Onduleur & batterie", required: true },
        { key: "photo_emplacement_batterie", label: "Emplacement de la batterie", category: "Onduleur & batterie", visibleIf: [{ field: "batterie_prevue", truthy: true }] },
      ],
    },
    {
      key: "cheminements",
      title: "Cheminements",
      short: "Cheminements",
      description: "Parcours des câbles DC/AC entre la toiture, l'onduleur et le comptage.",
      fields: [
        { key: "nb_segments", label: "Nombre de segments de cheminement", type: "number", required: true, min: 1, max: 8, help: "Un bloc de saisie sera créé pour chaque segment." },
        { key: "percements_necessaires", label: "Percements nécessaires", type: "select", required: true, options: OUI_NON },
        { key: "percement_nature", label: "Nature des parois à percer", type: "text", placeholder: "Béton 20 cm, brique, bardage…", visibleIf: [{ field: "percements_necessaires", equals: "oui" }] },
        { key: "gaine_existante", label: "Gaine / fourreau existant réutilisable", type: "boolean" },
        { key: "cheminement_notes", label: "Observations cheminement", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_cheminement_global", label: "Vue du parcours envisagé", instruction: "Montrez le trajet toiture → onduleur.", category: "Cheminements", required: true, multiple: true },
      ],
    },
    {
      key: "segments",
      title: "Segments de cheminement",
      short: "Segments",
      repeat: { countField: "nb_segments", itemLabel: "Segment", min: 1, max: 8 },
      fields: [
        { key: "segment_de_vers", label: "De … vers …", type: "text", required: true, placeholder: "Toiture pan 1 → combles" },
        { key: "segment_longueur", label: "Longueur", type: "number", unit: "m", required: true, min: 0, max: 300, step: 0.5 },
        {
          key: "segment_type",
          label: "Type de passage",
          type: "select",
          required: true,
          options: [
            { value: "apparent_interieur", label: "Apparent intérieur (goulotte)" },
            { value: "encastre", label: "Encastré" },
            { value: "combles", label: "Combles / vide sanitaire" },
            { value: "faux_plafond", label: "Faux plafond" },
            { value: "exterieur", label: "Extérieur (goulotte UV)" },
            { value: "enterre", label: "Enterré / tranchée" },
          ],
        },
        { key: "segment_tranchee_ml", label: "Métrage de tranchée", type: "number", unit: "m", min: 0, max: 300, visibleIf: [{ field: "segment_type", equals: "enterre" }] },
        { key: "segment_difficulte", label: "Difficulté particulière", type: "textarea", wide: true },
      ],
      photos: [
        { key: "photo_segment", label: "Photo du segment", instruction: "Point de départ et arrivée si possible.", category: "Cheminements", required: true, multiple: true },
      ],
    },
    {
      key: "contraintes",
      title: "Contraintes & points de vigilance",
      short: "Contraintes",
      kind: "constraints",
      description: "Consignez tout élément susceptible d'impacter le devis ou la pose.",
      fields: [
        { key: "contraintes_synthese", label: "Synthèse des contraintes", type: "textarea", wide: true, placeholder: "Résumé destiné au bureau d'études." },
        { key: "faisabilite", label: "Faisabilité technique", type: "select", required: true, options: [
          { value: "favorable", label: "Favorable" },
          { value: "favorable_reserves", label: "Favorable avec réserves" },
          { value: "a_etudier", label: "À étudier (bureau d'études)" },
          { value: "defavorable", label: "Défavorable" },
        ] },
      ],
      photos: [
        { key: "photo_contraintes", label: "Photos de contraintes", instruction: "Une photo par point de vigilance.", category: "Contraintes", multiple: true },
      ],
    },
    {
      key: "verification",
      title: "Vérification finale",
      short: "Vérification",
      kind: "review",
      description: "Contrôlez la complétude avant de clôturer la visite.",
      fields: [],
      photos: [],
    },
  ],
};
