/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ClientVerifyRouteImport } from './routes/client.verify'
import { Route as ClientProfilRouteImport } from './routes/client.profil'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientHistoriqueRouteImport } from './routes/client.historique'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as AuthenticatedUpgradeRequiredRouteImport } from './routes/_authenticated/upgrade-required'
import { Route as AuthenticatedTerrainRouteImport } from './routes/_authenticated/terrain'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedReservesRouteImport } from './routes/_authenticated/reserves'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEntrepriseRouteImport } from './routes/_authenticated/entreprise'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChantiersRouteImport } from './routes/_authenticated/chantiers'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedPvIndexRouteImport } from './routes/_authenticated/pv.index'
import { Route as SignPvTokenRouteImport } from './routes/sign.pv.$token'
import { Route as ClientPvIdRouteImport } from './routes/client.pv.$id'
import { Route as AuthenticatedTerrainIdRouteImport } from './routes/_authenticated/terrain.$id'
import { Route as AuthenticatedPvNewRouteImport } from './routes/_authenticated/pv.new'
import { Route as AuthenticatedPvIdRouteImport } from './routes/_authenticated/pv.$id'
import { Route as AuthenticatedParametresNotificationsRouteImport } from './routes/_authenticated/parametres.notifications'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin.monitoring'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksHealthRouteImport } from './routes/api/public/hooks/health'
import { Route as ApiPublicHooksCheckExpiringTrialsRouteImport } from './routes/api/public/hooks/check-expiring-trials'
import { Route as AuthenticatedPvIdHistoriqueRouteImport } from './routes/_authenticated/pv.$id.historique'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientVerifyRoute = ClientVerifyRouteImport.update({
  id: '/client/verify',
  path: '/client/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfilRoute = ClientProfilRouteImport.update({
  id: '/client/profil',
  path: '/client/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHistoriqueRoute = ClientHistoriqueRouteImport.update({
  id: '/client/historique',
  path: '/client/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradeRequiredRoute =
  AuthenticatedUpgradeRequiredRouteImport.update({
    id: '/upgrade-required',
    path: '/upgrade-required',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTerrainRoute = AuthenticatedTerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReservesRoute = AuthenticatedReservesRouteImport.update({
  id: '/reserves',
  path: '/reserves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntrepriseRoute = AuthenticatedEntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChantiersRoute = AuthenticatedChantiersRouteImport.update({
  id: '/chantiers',
  path: '/chantiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPvIndexRoute = AuthenticatedPvIndexRouteImport.update({
  id: '/pv/',
  path: '/pv/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SignPvTokenRoute = SignPvTokenRouteImport.update({
  id: '/sign/pv/$token',
  path: '/sign/pv/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPvIdRoute = ClientPvIdRouteImport.update({
  id: '/client/pv/$id',
  path: '/client/pv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTerrainIdRoute = AuthenticatedTerrainIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTerrainRoute,
} as any)
const AuthenticatedPvNewRoute = AuthenticatedPvNewRouteImport.update({
  id: '/pv/new',
  path: '/pv/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPvIdRoute = AuthenticatedPvIdRouteImport.update({
  id: '/pv/$id',
  path: '/pv/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParametresNotificationsRoute =
  AuthenticatedParametresNotificationsRouteImport.update({
    id: '/parametres/notifications',
    path: '/parametres/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/admin/monitoring',
    path: '/admin/monitoring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthRoute = ApiPublicHooksHealthRouteImport.update({
  id: '/api/public/hooks/health',
  path: '/api/public/hooks/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckExpiringTrialsRoute =
  ApiPublicHooksCheckExpiringTrialsRouteImport.update({
    id: '/api/public/hooks/check-expiring-trials',
    path: '/api/public/hooks/check-expiring-trials',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPvIdHistoriqueRoute =
  AuthenticatedPvIdHistoriqueRouteImport.update({
    id: '/historique',
    path: '/historique',
    getParentRoute: () => AuthenticatedPvIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chantiers': typeof AuthenticatedChantiersRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entreprise': typeof AuthenticatedEntrepriseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/reserves': typeof AuthenticatedReservesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/terrain': typeof AuthenticatedTerrainRouteWithChildren
  '/upgrade-required': typeof AuthenticatedUpgradeRequiredRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/historique': typeof ClientHistoriqueRoute
  '/client/login': typeof ClientLoginRoute
  '/client/profil': typeof ClientProfilRoute
  '/client/verify': typeof ClientVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/pv/$id': typeof AuthenticatedPvIdRouteWithChildren
  '/pv/new': typeof AuthenticatedPvNewRoute
  '/terrain/$id': typeof AuthenticatedTerrainIdRoute
  '/client/pv/$id': typeof ClientPvIdRoute
  '/sign/pv/$token': typeof SignPvTokenRoute
  '/pv/': typeof AuthenticatedPvIndexRoute
  '/pv/$id/historique': typeof AuthenticatedPvIdHistoriqueRoute
  '/api/public/hooks/check-expiring-trials': typeof ApiPublicHooksCheckExpiringTrialsRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chantiers': typeof AuthenticatedChantiersRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entreprise': typeof AuthenticatedEntrepriseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/reserves': typeof AuthenticatedReservesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/terrain': typeof AuthenticatedTerrainRouteWithChildren
  '/upgrade-required': typeof AuthenticatedUpgradeRequiredRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/historique': typeof ClientHistoriqueRoute
  '/client/login': typeof ClientLoginRoute
  '/client/profil': typeof ClientProfilRoute
  '/client/verify': typeof ClientVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/pv/$id': typeof AuthenticatedPvIdRouteWithChildren
  '/pv/new': typeof AuthenticatedPvNewRoute
  '/terrain/$id': typeof AuthenticatedTerrainIdRoute
  '/client/pv/$id': typeof ClientPvIdRoute
  '/sign/pv/$token': typeof SignPvTokenRoute
  '/pv': typeof AuthenticatedPvIndexRoute
  '/pv/$id/historique': typeof AuthenticatedPvIdHistoriqueRoute
  '/api/public/hooks/check-expiring-trials': typeof ApiPublicHooksCheckExpiringTrialsRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chantiers': typeof AuthenticatedChantiersRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entreprise': typeof AuthenticatedEntrepriseRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/reserves': typeof AuthenticatedReservesRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/_authenticated/terrain': typeof AuthenticatedTerrainRouteWithChildren
  '/_authenticated/upgrade-required': typeof AuthenticatedUpgradeRequiredRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/historique': typeof ClientHistoriqueRoute
  '/client/login': typeof ClientLoginRoute
  '/client/profil': typeof ClientProfilRoute
  '/client/verify': typeof ClientVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/_authenticated/pv/$id': typeof AuthenticatedPvIdRouteWithChildren
  '/_authenticated/pv/new': typeof AuthenticatedPvNewRoute
  '/_authenticated/terrain/$id': typeof AuthenticatedTerrainIdRoute
  '/client/pv/$id': typeof ClientPvIdRoute
  '/sign/pv/$token': typeof SignPvTokenRoute
  '/_authenticated/pv/': typeof AuthenticatedPvIndexRoute
  '/_authenticated/pv/$id/historique': typeof AuthenticatedPvIdHistoriqueRoute
  '/api/public/hooks/check-expiring-trials': typeof ApiPublicHooksCheckExpiringTrialsRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/verify'
    | '/billing'
    | '/chantiers'
    | '/clients'
    | '/dashboard'
    | '/entreprise'
    | '/equipe'
    | '/historique'
    | '/reserves'
    | '/statistiques'
    | '/terrain'
    | '/upgrade-required'
    | '/client/dashboard'
    | '/client/historique'
    | '/client/login'
    | '/client/profil'
    | '/client/verify'
    | '/invite/$token'
    | '/admin/monitoring'
    | '/parametres/notifications'
    | '/pv/$id'
    | '/pv/new'
    | '/terrain/$id'
    | '/client/pv/$id'
    | '/sign/pv/$token'
    | '/pv/'
    | '/pv/$id/historique'
    | '/api/public/hooks/check-expiring-trials'
    | '/api/public/hooks/health'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/verify'
    | '/billing'
    | '/chantiers'
    | '/clients'
    | '/dashboard'
    | '/entreprise'
    | '/equipe'
    | '/historique'
    | '/reserves'
    | '/statistiques'
    | '/terrain'
    | '/upgrade-required'
    | '/client/dashboard'
    | '/client/historique'
    | '/client/login'
    | '/client/profil'
    | '/client/verify'
    | '/invite/$token'
    | '/admin/monitoring'
    | '/parametres/notifications'
    | '/pv/$id'
    | '/pv/new'
    | '/terrain/$id'
    | '/client/pv/$id'
    | '/sign/pv/$token'
    | '/pv'
    | '/pv/$id/historique'
    | '/api/public/hooks/check-expiring-trials'
    | '/api/public/hooks/health'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/verify'
    | '/_authenticated/billing'
    | '/_authenticated/chantiers'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/entreprise'
    | '/_authenticated/equipe'
    | '/_authenticated/historique'
    | '/_authenticated/reserves'
    | '/_authenticated/statistiques'
    | '/_authenticated/terrain'
    | '/_authenticated/upgrade-required'
    | '/client/dashboard'
    | '/client/historique'
    | '/client/login'
    | '/client/profil'
    | '/client/verify'
    | '/invite/$token'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/parametres/notifications'
    | '/_authenticated/pv/$id'
    | '/_authenticated/pv/new'
    | '/_authenticated/terrain/$id'
    | '/client/pv/$id'
    | '/sign/pv/$token'
    | '/_authenticated/pv/'
    | '/_authenticated/pv/$id/historique'
    | '/api/public/hooks/check-expiring-trials'
    | '/api/public/hooks/health'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientHistoriqueRoute: typeof ClientHistoriqueRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientProfilRoute: typeof ClientProfilRoute
  ClientVerifyRoute: typeof ClientVerifyRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ClientPvIdRoute: typeof ClientPvIdRoute
  SignPvTokenRoute: typeof SignPvTokenRoute
  ApiPublicHooksCheckExpiringTrialsRoute: typeof ApiPublicHooksCheckExpiringTrialsRoute
  ApiPublicHooksHealthRoute: typeof ApiPublicHooksHealthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/verify': {
      id: '/client/verify'
      path: '/client/verify'
      fullPath: '/client/verify'
      preLoaderRoute: typeof ClientVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profil': {
      id: '/client/profil'
      path: '/client/profil'
      fullPath: '/client/profil'
      preLoaderRoute: typeof ClientProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/historique': {
      id: '/client/historique'
      path: '/client/historique'
      fullPath: '/client/historique'
      preLoaderRoute: typeof ClientHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrade-required': {
      id: '/_authenticated/upgrade-required'
      path: '/upgrade-required'
      fullPath: '/upgrade-required'
      preLoaderRoute: typeof AuthenticatedUpgradeRequiredRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terrain': {
      id: '/_authenticated/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof AuthenticatedTerrainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reserves': {
      id: '/_authenticated/reserves'
      path: '/reserves'
      fullPath: '/reserves'
      preLoaderRoute: typeof AuthenticatedReservesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entreprise': {
      id: '/_authenticated/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof AuthenticatedEntrepriseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chantiers': {
      id: '/_authenticated/chantiers'
      path: '/chantiers'
      fullPath: '/chantiers'
      preLoaderRoute: typeof AuthenticatedChantiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pv/': {
      id: '/_authenticated/pv/'
      path: '/pv'
      fullPath: '/pv/'
      preLoaderRoute: typeof AuthenticatedPvIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/sign/pv/$token': {
      id: '/sign/pv/$token'
      path: '/sign/pv/$token'
      fullPath: '/sign/pv/$token'
      preLoaderRoute: typeof SignPvTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/pv/$id': {
      id: '/client/pv/$id'
      path: '/client/pv/$id'
      fullPath: '/client/pv/$id'
      preLoaderRoute: typeof ClientPvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/terrain/$id': {
      id: '/_authenticated/terrain/$id'
      path: '/$id'
      fullPath: '/terrain/$id'
      preLoaderRoute: typeof AuthenticatedTerrainIdRouteImport
      parentRoute: typeof AuthenticatedTerrainRoute
    }
    '/_authenticated/pv/new': {
      id: '/_authenticated/pv/new'
      path: '/pv/new'
      fullPath: '/pv/new'
      preLoaderRoute: typeof AuthenticatedPvNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pv/$id': {
      id: '/_authenticated/pv/$id'
      path: '/pv/$id'
      fullPath: '/pv/$id'
      preLoaderRoute: typeof AuthenticatedPvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres/notifications': {
      id: '/_authenticated/parametres/notifications'
      path: '/parametres/notifications'
      fullPath: '/parametres/notifications'
      preLoaderRoute: typeof AuthenticatedParametresNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health': {
      id: '/api/public/hooks/health'
      path: '/api/public/hooks/health'
      fullPath: '/api/public/hooks/health'
      preLoaderRoute: typeof ApiPublicHooksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-expiring-trials': {
      id: '/api/public/hooks/check-expiring-trials'
      path: '/api/public/hooks/check-expiring-trials'
      fullPath: '/api/public/hooks/check-expiring-trials'
      preLoaderRoute: typeof ApiPublicHooksCheckExpiringTrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pv/$id/historique': {
      id: '/_authenticated/pv/$id/historique'
      path: '/historique'
      fullPath: '/pv/$id/historique'
      preLoaderRoute: typeof AuthenticatedPvIdHistoriqueRouteImport
      parentRoute: typeof AuthenticatedPvIdRoute
    }
  }
}

interface AuthenticatedTerrainRouteChildren {
  AuthenticatedTerrainIdRoute: typeof AuthenticatedTerrainIdRoute
}

const AuthenticatedTerrainRouteChildren: AuthenticatedTerrainRouteChildren = {
  AuthenticatedTerrainIdRoute: AuthenticatedTerrainIdRoute,
}

const AuthenticatedTerrainRouteWithChildren =
  AuthenticatedTerrainRoute._addFileChildren(AuthenticatedTerrainRouteChildren)

interface AuthenticatedPvIdRouteChildren {
  AuthenticatedPvIdHistoriqueRoute: typeof AuthenticatedPvIdHistoriqueRoute
}

const AuthenticatedPvIdRouteChildren: AuthenticatedPvIdRouteChildren = {
  AuthenticatedPvIdHistoriqueRoute: AuthenticatedPvIdHistoriqueRoute,
}

const AuthenticatedPvIdRouteWithChildren =
  AuthenticatedPvIdRoute._addFileChildren(AuthenticatedPvIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChantiersRoute: typeof AuthenticatedChantiersRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntrepriseRoute: typeof AuthenticatedEntrepriseRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedReservesRoute: typeof AuthenticatedReservesRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedTerrainRoute: typeof AuthenticatedTerrainRouteWithChildren
  AuthenticatedUpgradeRequiredRoute: typeof AuthenticatedUpgradeRequiredRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedParametresNotificationsRoute: typeof AuthenticatedParametresNotificationsRoute
  AuthenticatedPvIdRoute: typeof AuthenticatedPvIdRouteWithChildren
  AuthenticatedPvNewRoute: typeof AuthenticatedPvNewRoute
  AuthenticatedPvIndexRoute: typeof AuthenticatedPvIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChantiersRoute: AuthenticatedChantiersRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntrepriseRoute: AuthenticatedEntrepriseRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedReservesRoute: AuthenticatedReservesRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedTerrainRoute: AuthenticatedTerrainRouteWithChildren,
  AuthenticatedUpgradeRequiredRoute: AuthenticatedUpgradeRequiredRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
  AuthenticatedParametresNotificationsRoute:
    AuthenticatedParametresNotificationsRoute,
  AuthenticatedPvIdRoute: AuthenticatedPvIdRouteWithChildren,
  AuthenticatedPvNewRoute: AuthenticatedPvNewRoute,
  AuthenticatedPvIndexRoute: AuthenticatedPvIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientHistoriqueRoute: ClientHistoriqueRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientProfilRoute: ClientProfilRoute,
  ClientVerifyRoute: ClientVerifyRoute,
  InviteTokenRoute: InviteTokenRoute,
  ClientPvIdRoute: ClientPvIdRoute,
  SignPvTokenRoute: SignPvTokenRoute,
  ApiPublicHooksCheckExpiringTrialsRoute:
    ApiPublicHooksCheckExpiringTrialsRoute,
  ApiPublicHooksHealthRoute: ApiPublicHooksHealthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
