/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ClientVerifyRouteImport } from './routes/client.verify'
import { Route as ClientProfilRouteImport } from './routes/client.profil'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientHistoriqueRouteImport } from './routes/client.historique'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as AuthenticatedUpgradeRequiredRouteImport } from './routes/_authenticated/upgrade-required'
import { Route as AuthenticatedTerrainRouteImport } from './routes/_authenticated/terrain'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedReservesRouteImport } from './routes/_authenticated/reserves'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEntrepriseRouteImport } from './routes/_authenticated/entreprise'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChantiersRouteImport } from './routes/_authenticated/chantiers'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAccountSuspendedRouteImport } from './routes/_authenticated/account-suspended'
import { Route as AuthenticatedPvIndexRouteImport } from './routes/_authenticated/pv.index'
import { Route as AuthenticatedParametresIndexRouteImport } from './routes/_authenticated/parametres.index'
import { Route as SignPvTokenRouteImport } from './routes/sign.pv.$token'
import { Route as ClientPvIdRouteImport } from './routes/client.pv.$id'
import { Route as AuthenticatedTerrainIdRouteImport } from './routes/_authenticated/terrain.$id'
import { Route as AuthenticatedPvNewRouteImport } from './routes/_authenticated/pv.new'
import { Route as AuthenticatedPvIdRouteImport } from './routes/_authenticated/pv.$id'
import { Route as AuthenticatedParametresSecuriteRouteImport } from './routes/_authenticated/parametres.securite'
import { Route as AuthenticatedParametresPreferencesRouteImport } from './routes/_authenticated/parametres.preferences'
import { Route as AuthenticatedParametresNumerotationRouteImport } from './routes/_authenticated/parametres.numerotation'
import { Route as AuthenticatedParametresNotificationsRouteImport } from './routes/_authenticated/parametres.notifications'
import { Route as AuthenticatedParametresIntegrationsRouteImport } from './routes/_authenticated/parametres.integrations'
import { Route as AuthenticatedParametresDonneesRouteImport } from './routes/_authenticated/parametres.donnees'
import { Route as AuthenticatedParametresBrandingRouteImport } from './routes/_authenticated/parametres.branding'
import { Route as AuthenticatedParametresAuditRouteImport } from './routes/_authenticated/parametres.audit'
import { Route as AuthenticatedParametresApiRouteImport } from './routes/_authenticated/parametres.api'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin.monitoring'
import { Route as AuthenticatedAdminLaunchChecklistRouteImport } from './routes/_authenticated/admin.launch-checklist'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminSupportIndexRouteImport } from './routes/_authenticated/admin.support.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksHealthRouteImport } from './routes/api/public/hooks/health'
import { Route as ApiPublicHooksDrainWebhooksRouteImport } from './routes/api/public/hooks/drain-webhooks'
import { Route as ApiPublicHooksDrainEmailsRouteImport } from './routes/api/public/hooks/drain-emails'
import { Route as ApiPublicHooksCheckExpiringTrialsRouteImport } from './routes/api/public/hooks/check-expiring-trials'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar/$token'
import { Route as AuthenticatedPvIdLeveeReservesRouteImport } from './routes/_authenticated/pv.$id.levee-reserves'
import { Route as AuthenticatedPvIdHistoriqueRouteImport } from './routes/_authenticated/pv.$id.historique'
import { Route as AuthenticatedAdminSupportCompanyIdRouteImport } from './routes/_authenticated/admin.support.$companyId'
import { Route as AuthenticatedAdminCompaniesIdRouteImport } from './routes/_authenticated/admin.companies.$id'
import { Route as ClientPvIdLeveeReservesLiftIdRouteImport } from './routes/client.pv.$id.levee-reserves.$liftId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientVerifyRoute = ClientVerifyRouteImport.update({
  id: '/client/verify',
  path: '/client/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfilRoute = ClientProfilRouteImport.update({
  id: '/client/profil',
  path: '/client/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHistoriqueRoute = ClientHistoriqueRouteImport.update({
  id: '/client/historique',
  path: '/client/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradeRequiredRoute =
  AuthenticatedUpgradeRequiredRouteImport.update({
    id: '/upgrade-required',
    path: '/upgrade-required',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTerrainRoute = AuthenticatedTerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReservesRoute = AuthenticatedReservesRouteImport.update({
  id: '/reserves',
  path: '/reserves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntrepriseRoute = AuthenticatedEntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChantiersRoute = AuthenticatedChantiersRouteImport.update({
  id: '/chantiers',
  path: '/chantiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountSuspendedRoute =
  AuthenticatedAccountSuspendedRouteImport.update({
    id: '/account-suspended',
    path: '/account-suspended',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPvIndexRoute = AuthenticatedPvIndexRouteImport.update({
  id: '/pv/',
  path: '/pv/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParametresIndexRoute =
  AuthenticatedParametresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const SignPvTokenRoute = SignPvTokenRouteImport.update({
  id: '/sign/pv/$token',
  path: '/sign/pv/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPvIdRoute = ClientPvIdRouteImport.update({
  id: '/client/pv/$id',
  path: '/client/pv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTerrainIdRoute = AuthenticatedTerrainIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTerrainRoute,
} as any)
const AuthenticatedPvNewRoute = AuthenticatedPvNewRouteImport.update({
  id: '/pv/new',
  path: '/pv/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPvIdRoute = AuthenticatedPvIdRouteImport.update({
  id: '/pv/$id',
  path: '/pv/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParametresSecuriteRoute =
  AuthenticatedParametresSecuriteRouteImport.update({
    id: '/securite',
    path: '/securite',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresPreferencesRoute =
  AuthenticatedParametresPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresNumerotationRoute =
  AuthenticatedParametresNumerotationRouteImport.update({
    id: '/numerotation',
    path: '/numerotation',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresNotificationsRoute =
  AuthenticatedParametresNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresIntegrationsRoute =
  AuthenticatedParametresIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresDonneesRoute =
  AuthenticatedParametresDonneesRouteImport.update({
    id: '/donnees',
    path: '/donnees',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresBrandingRoute =
  AuthenticatedParametresBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresAuditRoute =
  AuthenticatedParametresAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresApiRoute =
  AuthenticatedParametresApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/admin/monitoring',
    path: '/admin/monitoring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLaunchChecklistRoute =
  AuthenticatedAdminLaunchChecklistRouteImport.update({
    id: '/admin/launch-checklist',
    path: '/admin/launch-checklist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/admin/companies',
    path: '/admin/companies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSupportIndexRoute =
  AuthenticatedAdminSupportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSupportRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthRoute = ApiPublicHooksHealthRouteImport.update({
  id: '/api/public/hooks/health',
  path: '/api/public/hooks/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDrainWebhooksRoute =
  ApiPublicHooksDrainWebhooksRouteImport.update({
    id: '/api/public/hooks/drain-webhooks',
    path: '/api/public/hooks/drain-webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDrainEmailsRoute =
  ApiPublicHooksDrainEmailsRouteImport.update({
    id: '/api/public/hooks/drain-emails',
    path: '/api/public/hooks/drain-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckExpiringTrialsRoute =
  ApiPublicHooksCheckExpiringTrialsRouteImport.update({
    id: '/api/public/hooks/check-expiring-trials',
    path: '/api/public/hooks/check-expiring-trials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPvIdLeveeReservesRoute =
  AuthenticatedPvIdLeveeReservesRouteImport.update({
    id: '/levee-reserves',
    path: '/levee-reserves',
    getParentRoute: () => AuthenticatedPvIdRoute,
  } as any)
const AuthenticatedPvIdHistoriqueRoute =
  AuthenticatedPvIdHistoriqueRouteImport.update({
    id: '/historique',
    path: '/historique',
    getParentRoute: () => AuthenticatedPvIdRoute,
  } as any)
const AuthenticatedAdminSupportCompanyIdRoute =
  AuthenticatedAdminSupportCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedAdminSupportRoute,
  } as any)
const AuthenticatedAdminCompaniesIdRoute =
  AuthenticatedAdminCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCompaniesRoute,
  } as any)
const ClientPvIdLeveeReservesLiftIdRoute =
  ClientPvIdLeveeReservesLiftIdRouteImport.update({
    id: '/levee-reserves/$liftId',
    path: '/levee-reserves/$liftId',
    getParentRoute: () => ClientPvIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions': typeof MentionsRoute
  '/securite': typeof SecuriteRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verify': typeof VerifyRoute
  '/account-suspended': typeof AuthenticatedAccountSuspendedRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chantiers': typeof AuthenticatedChantiersRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entreprise': typeof AuthenticatedEntrepriseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/reserves': typeof AuthenticatedReservesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/terrain': typeof AuthenticatedTerrainRouteWithChildren
  '/upgrade-required': typeof AuthenticatedUpgradeRequiredRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/historique': typeof ClientHistoriqueRoute
  '/client/login': typeof ClientLoginRoute
  '/client/profil': typeof ClientProfilRoute
  '/client/verify': typeof ClientVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/launch-checklist': typeof AuthenticatedAdminLaunchChecklistRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/parametres/api': typeof AuthenticatedParametresApiRoute
  '/parametres/audit': typeof AuthenticatedParametresAuditRoute
  '/parametres/branding': typeof AuthenticatedParametresBrandingRoute
  '/parametres/donnees': typeof AuthenticatedParametresDonneesRoute
  '/parametres/integrations': typeof AuthenticatedParametresIntegrationsRoute
  '/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/parametres/numerotation': typeof AuthenticatedParametresNumerotationRoute
  '/parametres/preferences': typeof AuthenticatedParametresPreferencesRoute
  '/parametres/securite': typeof AuthenticatedParametresSecuriteRoute
  '/pv/$id': typeof AuthenticatedPvIdRouteWithChildren
  '/pv/new': typeof AuthenticatedPvNewRoute
  '/terrain/$id': typeof AuthenticatedTerrainIdRoute
  '/client/pv/$id': typeof ClientPvIdRouteWithChildren
  '/sign/pv/$token': typeof SignPvTokenRoute
  '/parametres/': typeof AuthenticatedParametresIndexRoute
  '/pv/': typeof AuthenticatedPvIndexRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/support/$companyId': typeof AuthenticatedAdminSupportCompanyIdRoute
  '/pv/$id/historique': typeof AuthenticatedPvIdHistoriqueRoute
  '/pv/$id/levee-reserves': typeof AuthenticatedPvIdLeveeReservesRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/check-expiring-trials': typeof ApiPublicHooksCheckExpiringTrialsRoute
  '/api/public/hooks/drain-emails': typeof ApiPublicHooksDrainEmailsRoute
  '/api/public/hooks/drain-webhooks': typeof ApiPublicHooksDrainWebhooksRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/client/pv/$id/levee-reserves/$liftId': typeof ClientPvIdLeveeReservesLiftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions': typeof MentionsRoute
  '/securite': typeof SecuriteRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verify': typeof VerifyRoute
  '/account-suspended': typeof AuthenticatedAccountSuspendedRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chantiers': typeof AuthenticatedChantiersRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entreprise': typeof AuthenticatedEntrepriseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reserves': typeof AuthenticatedReservesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/terrain': typeof AuthenticatedTerrainRouteWithChildren
  '/upgrade-required': typeof AuthenticatedUpgradeRequiredRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/historique': typeof ClientHistoriqueRoute
  '/client/login': typeof ClientLoginRoute
  '/client/profil': typeof ClientProfilRoute
  '/client/verify': typeof ClientVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/launch-checklist': typeof AuthenticatedAdminLaunchChecklistRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/parametres/api': typeof AuthenticatedParametresApiRoute
  '/parametres/audit': typeof AuthenticatedParametresAuditRoute
  '/parametres/branding': typeof AuthenticatedParametresBrandingRoute
  '/parametres/donnees': typeof AuthenticatedParametresDonneesRoute
  '/parametres/integrations': typeof AuthenticatedParametresIntegrationsRoute
  '/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/parametres/numerotation': typeof AuthenticatedParametresNumerotationRoute
  '/parametres/preferences': typeof AuthenticatedParametresPreferencesRoute
  '/parametres/securite': typeof AuthenticatedParametresSecuriteRoute
  '/pv/$id': typeof AuthenticatedPvIdRouteWithChildren
  '/pv/new': typeof AuthenticatedPvNewRoute
  '/terrain/$id': typeof AuthenticatedTerrainIdRoute
  '/client/pv/$id': typeof ClientPvIdRouteWithChildren
  '/sign/pv/$token': typeof SignPvTokenRoute
  '/parametres': typeof AuthenticatedParametresIndexRoute
  '/pv': typeof AuthenticatedPvIndexRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/support/$companyId': typeof AuthenticatedAdminSupportCompanyIdRoute
  '/pv/$id/historique': typeof AuthenticatedPvIdHistoriqueRoute
  '/pv/$id/levee-reserves': typeof AuthenticatedPvIdLeveeReservesRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/check-expiring-trials': typeof ApiPublicHooksCheckExpiringTrialsRoute
  '/api/public/hooks/drain-emails': typeof ApiPublicHooksDrainEmailsRoute
  '/api/public/hooks/drain-webhooks': typeof ApiPublicHooksDrainWebhooksRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/support': typeof AuthenticatedAdminSupportIndexRoute
  '/client/pv/$id/levee-reserves/$liftId': typeof ClientPvIdLeveeReservesLiftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions': typeof MentionsRoute
  '/securite': typeof SecuriteRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/account-suspended': typeof AuthenticatedAccountSuspendedRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chantiers': typeof AuthenticatedChantiersRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entreprise': typeof AuthenticatedEntrepriseRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/_authenticated/reserves': typeof AuthenticatedReservesRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/_authenticated/terrain': typeof AuthenticatedTerrainRouteWithChildren
  '/_authenticated/upgrade-required': typeof AuthenticatedUpgradeRequiredRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/historique': typeof ClientHistoriqueRoute
  '/client/login': typeof ClientLoginRoute
  '/client/profil': typeof ClientProfilRoute
  '/client/verify': typeof ClientVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/launch-checklist': typeof AuthenticatedAdminLaunchChecklistRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/_authenticated/parametres/api': typeof AuthenticatedParametresApiRoute
  '/_authenticated/parametres/audit': typeof AuthenticatedParametresAuditRoute
  '/_authenticated/parametres/branding': typeof AuthenticatedParametresBrandingRoute
  '/_authenticated/parametres/donnees': typeof AuthenticatedParametresDonneesRoute
  '/_authenticated/parametres/integrations': typeof AuthenticatedParametresIntegrationsRoute
  '/_authenticated/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/_authenticated/parametres/numerotation': typeof AuthenticatedParametresNumerotationRoute
  '/_authenticated/parametres/preferences': typeof AuthenticatedParametresPreferencesRoute
  '/_authenticated/parametres/securite': typeof AuthenticatedParametresSecuriteRoute
  '/_authenticated/pv/$id': typeof AuthenticatedPvIdRouteWithChildren
  '/_authenticated/pv/new': typeof AuthenticatedPvNewRoute
  '/_authenticated/terrain/$id': typeof AuthenticatedTerrainIdRoute
  '/client/pv/$id': typeof ClientPvIdRouteWithChildren
  '/sign/pv/$token': typeof SignPvTokenRoute
  '/_authenticated/parametres/': typeof AuthenticatedParametresIndexRoute
  '/_authenticated/pv/': typeof AuthenticatedPvIndexRoute
  '/_authenticated/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/_authenticated/admin/support/$companyId': typeof AuthenticatedAdminSupportCompanyIdRoute
  '/_authenticated/pv/$id/historique': typeof AuthenticatedPvIdHistoriqueRoute
  '/_authenticated/pv/$id/levee-reserves': typeof AuthenticatedPvIdLeveeReservesRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/check-expiring-trials': typeof ApiPublicHooksCheckExpiringTrialsRoute
  '/api/public/hooks/drain-emails': typeof ApiPublicHooksDrainEmailsRoute
  '/api/public/hooks/drain-webhooks': typeof ApiPublicHooksDrainWebhooksRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/client/pv/$id/levee-reserves/$liftId': typeof ClientPvIdLeveeReservesLiftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgv'
    | '/confidentialite'
    | '/login'
    | '/mentions'
    | '/securite'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verify'
    | '/account-suspended'
    | '/billing'
    | '/chantiers'
    | '/clients'
    | '/dashboard'
    | '/entreprise'
    | '/equipe'
    | '/historique'
    | '/onboarding'
    | '/parametres'
    | '/reserves'
    | '/statistiques'
    | '/terrain'
    | '/upgrade-required'
    | '/client/dashboard'
    | '/client/historique'
    | '/client/login'
    | '/client/profil'
    | '/client/verify'
    | '/invite/$token'
    | '/admin/billing'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/launch-checklist'
    | '/admin/monitoring'
    | '/admin/support'
    | '/parametres/api'
    | '/parametres/audit'
    | '/parametres/branding'
    | '/parametres/donnees'
    | '/parametres/integrations'
    | '/parametres/notifications'
    | '/parametres/numerotation'
    | '/parametres/preferences'
    | '/parametres/securite'
    | '/pv/$id'
    | '/pv/new'
    | '/terrain/$id'
    | '/client/pv/$id'
    | '/sign/pv/$token'
    | '/parametres/'
    | '/pv/'
    | '/admin/companies/$id'
    | '/admin/support/$companyId'
    | '/pv/$id/historique'
    | '/pv/$id/levee-reserves'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/check-expiring-trials'
    | '/api/public/hooks/drain-emails'
    | '/api/public/hooks/drain-webhooks'
    | '/api/public/hooks/health'
    | '/api/public/payments/webhook'
    | '/admin/support/'
    | '/client/pv/$id/levee-reserves/$liftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgv'
    | '/confidentialite'
    | '/login'
    | '/mentions'
    | '/securite'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verify'
    | '/account-suspended'
    | '/billing'
    | '/chantiers'
    | '/clients'
    | '/dashboard'
    | '/entreprise'
    | '/equipe'
    | '/historique'
    | '/onboarding'
    | '/reserves'
    | '/statistiques'
    | '/terrain'
    | '/upgrade-required'
    | '/client/dashboard'
    | '/client/historique'
    | '/client/login'
    | '/client/profil'
    | '/client/verify'
    | '/invite/$token'
    | '/admin/billing'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/launch-checklist'
    | '/admin/monitoring'
    | '/parametres/api'
    | '/parametres/audit'
    | '/parametres/branding'
    | '/parametres/donnees'
    | '/parametres/integrations'
    | '/parametres/notifications'
    | '/parametres/numerotation'
    | '/parametres/preferences'
    | '/parametres/securite'
    | '/pv/$id'
    | '/pv/new'
    | '/terrain/$id'
    | '/client/pv/$id'
    | '/sign/pv/$token'
    | '/parametres'
    | '/pv'
    | '/admin/companies/$id'
    | '/admin/support/$companyId'
    | '/pv/$id/historique'
    | '/pv/$id/levee-reserves'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/check-expiring-trials'
    | '/api/public/hooks/drain-emails'
    | '/api/public/hooks/drain-webhooks'
    | '/api/public/hooks/health'
    | '/api/public/payments/webhook'
    | '/admin/support'
    | '/client/pv/$id/levee-reserves/$liftId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cgv'
    | '/confidentialite'
    | '/login'
    | '/mentions'
    | '/securite'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verify'
    | '/_authenticated/account-suspended'
    | '/_authenticated/billing'
    | '/_authenticated/chantiers'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/entreprise'
    | '/_authenticated/equipe'
    | '/_authenticated/historique'
    | '/_authenticated/onboarding'
    | '/_authenticated/parametres'
    | '/_authenticated/reserves'
    | '/_authenticated/statistiques'
    | '/_authenticated/terrain'
    | '/_authenticated/upgrade-required'
    | '/client/dashboard'
    | '/client/historique'
    | '/client/login'
    | '/client/profil'
    | '/client/verify'
    | '/invite/$token'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/launch-checklist'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/admin/support'
    | '/_authenticated/parametres/api'
    | '/_authenticated/parametres/audit'
    | '/_authenticated/parametres/branding'
    | '/_authenticated/parametres/donnees'
    | '/_authenticated/parametres/integrations'
    | '/_authenticated/parametres/notifications'
    | '/_authenticated/parametres/numerotation'
    | '/_authenticated/parametres/preferences'
    | '/_authenticated/parametres/securite'
    | '/_authenticated/pv/$id'
    | '/_authenticated/pv/new'
    | '/_authenticated/terrain/$id'
    | '/client/pv/$id'
    | '/sign/pv/$token'
    | '/_authenticated/parametres/'
    | '/_authenticated/pv/'
    | '/_authenticated/admin/companies/$id'
    | '/_authenticated/admin/support/$companyId'
    | '/_authenticated/pv/$id/historique'
    | '/_authenticated/pv/$id/levee-reserves'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/check-expiring-trials'
    | '/api/public/hooks/drain-emails'
    | '/api/public/hooks/drain-webhooks'
    | '/api/public/hooks/health'
    | '/api/public/payments/webhook'
    | '/_authenticated/admin/support/'
    | '/client/pv/$id/levee-reserves/$liftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  LoginRoute: typeof LoginRoute
  MentionsRoute: typeof MentionsRoute
  SecuriteRoute: typeof SecuriteRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  VerifyRoute: typeof VerifyRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientHistoriqueRoute: typeof ClientHistoriqueRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientProfilRoute: typeof ClientProfilRoute
  ClientVerifyRoute: typeof ClientVerifyRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ClientPvIdRoute: typeof ClientPvIdRouteWithChildren
  SignPvTokenRoute: typeof SignPvTokenRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicHooksCheckExpiringTrialsRoute: typeof ApiPublicHooksCheckExpiringTrialsRoute
  ApiPublicHooksDrainEmailsRoute: typeof ApiPublicHooksDrainEmailsRoute
  ApiPublicHooksDrainWebhooksRoute: typeof ApiPublicHooksDrainWebhooksRoute
  ApiPublicHooksHealthRoute: typeof ApiPublicHooksHealthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/verify': {
      id: '/client/verify'
      path: '/client/verify'
      fullPath: '/client/verify'
      preLoaderRoute: typeof ClientVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profil': {
      id: '/client/profil'
      path: '/client/profil'
      fullPath: '/client/profil'
      preLoaderRoute: typeof ClientProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/historique': {
      id: '/client/historique'
      path: '/client/historique'
      fullPath: '/client/historique'
      preLoaderRoute: typeof ClientHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrade-required': {
      id: '/_authenticated/upgrade-required'
      path: '/upgrade-required'
      fullPath: '/upgrade-required'
      preLoaderRoute: typeof AuthenticatedUpgradeRequiredRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terrain': {
      id: '/_authenticated/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof AuthenticatedTerrainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reserves': {
      id: '/_authenticated/reserves'
      path: '/reserves'
      fullPath: '/reserves'
      preLoaderRoute: typeof AuthenticatedReservesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entreprise': {
      id: '/_authenticated/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof AuthenticatedEntrepriseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chantiers': {
      id: '/_authenticated/chantiers'
      path: '/chantiers'
      fullPath: '/chantiers'
      preLoaderRoute: typeof AuthenticatedChantiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account-suspended': {
      id: '/_authenticated/account-suspended'
      path: '/account-suspended'
      fullPath: '/account-suspended'
      preLoaderRoute: typeof AuthenticatedAccountSuspendedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pv/': {
      id: '/_authenticated/pv/'
      path: '/pv'
      fullPath: '/pv/'
      preLoaderRoute: typeof AuthenticatedPvIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres/': {
      id: '/_authenticated/parametres/'
      path: '/'
      fullPath: '/parametres/'
      preLoaderRoute: typeof AuthenticatedParametresIndexRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/sign/pv/$token': {
      id: '/sign/pv/$token'
      path: '/sign/pv/$token'
      fullPath: '/sign/pv/$token'
      preLoaderRoute: typeof SignPvTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/pv/$id': {
      id: '/client/pv/$id'
      path: '/client/pv/$id'
      fullPath: '/client/pv/$id'
      preLoaderRoute: typeof ClientPvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/terrain/$id': {
      id: '/_authenticated/terrain/$id'
      path: '/$id'
      fullPath: '/terrain/$id'
      preLoaderRoute: typeof AuthenticatedTerrainIdRouteImport
      parentRoute: typeof AuthenticatedTerrainRoute
    }
    '/_authenticated/pv/new': {
      id: '/_authenticated/pv/new'
      path: '/pv/new'
      fullPath: '/pv/new'
      preLoaderRoute: typeof AuthenticatedPvNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pv/$id': {
      id: '/_authenticated/pv/$id'
      path: '/pv/$id'
      fullPath: '/pv/$id'
      preLoaderRoute: typeof AuthenticatedPvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres/securite': {
      id: '/_authenticated/parametres/securite'
      path: '/securite'
      fullPath: '/parametres/securite'
      preLoaderRoute: typeof AuthenticatedParametresSecuriteRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/preferences': {
      id: '/_authenticated/parametres/preferences'
      path: '/preferences'
      fullPath: '/parametres/preferences'
      preLoaderRoute: typeof AuthenticatedParametresPreferencesRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/numerotation': {
      id: '/_authenticated/parametres/numerotation'
      path: '/numerotation'
      fullPath: '/parametres/numerotation'
      preLoaderRoute: typeof AuthenticatedParametresNumerotationRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/notifications': {
      id: '/_authenticated/parametres/notifications'
      path: '/notifications'
      fullPath: '/parametres/notifications'
      preLoaderRoute: typeof AuthenticatedParametresNotificationsRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/integrations': {
      id: '/_authenticated/parametres/integrations'
      path: '/integrations'
      fullPath: '/parametres/integrations'
      preLoaderRoute: typeof AuthenticatedParametresIntegrationsRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/donnees': {
      id: '/_authenticated/parametres/donnees'
      path: '/donnees'
      fullPath: '/parametres/donnees'
      preLoaderRoute: typeof AuthenticatedParametresDonneesRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/branding': {
      id: '/_authenticated/parametres/branding'
      path: '/branding'
      fullPath: '/parametres/branding'
      preLoaderRoute: typeof AuthenticatedParametresBrandingRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/audit': {
      id: '/_authenticated/parametres/audit'
      path: '/audit'
      fullPath: '/parametres/audit'
      preLoaderRoute: typeof AuthenticatedParametresAuditRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/api': {
      id: '/_authenticated/parametres/api'
      path: '/api'
      fullPath: '/parametres/api'
      preLoaderRoute: typeof AuthenticatedParametresApiRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/launch-checklist': {
      id: '/_authenticated/admin/launch-checklist'
      path: '/admin/launch-checklist'
      fullPath: '/admin/launch-checklist'
      preLoaderRoute: typeof AuthenticatedAdminLaunchChecklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support/': {
      id: '/_authenticated/admin/support/'
      path: '/'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AuthenticatedAdminSupportIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSupportRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health': {
      id: '/api/public/hooks/health'
      path: '/api/public/hooks/health'
      fullPath: '/api/public/hooks/health'
      preLoaderRoute: typeof ApiPublicHooksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-webhooks': {
      id: '/api/public/hooks/drain-webhooks'
      path: '/api/public/hooks/drain-webhooks'
      fullPath: '/api/public/hooks/drain-webhooks'
      preLoaderRoute: typeof ApiPublicHooksDrainWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-emails': {
      id: '/api/public/hooks/drain-emails'
      path: '/api/public/hooks/drain-emails'
      fullPath: '/api/public/hooks/drain-emails'
      preLoaderRoute: typeof ApiPublicHooksDrainEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-expiring-trials': {
      id: '/api/public/hooks/check-expiring-trials'
      path: '/api/public/hooks/check-expiring-trials'
      fullPath: '/api/public/hooks/check-expiring-trials'
      preLoaderRoute: typeof ApiPublicHooksCheckExpiringTrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pv/$id/levee-reserves': {
      id: '/_authenticated/pv/$id/levee-reserves'
      path: '/levee-reserves'
      fullPath: '/pv/$id/levee-reserves'
      preLoaderRoute: typeof AuthenticatedPvIdLeveeReservesRouteImport
      parentRoute: typeof AuthenticatedPvIdRoute
    }
    '/_authenticated/pv/$id/historique': {
      id: '/_authenticated/pv/$id/historique'
      path: '/historique'
      fullPath: '/pv/$id/historique'
      preLoaderRoute: typeof AuthenticatedPvIdHistoriqueRouteImport
      parentRoute: typeof AuthenticatedPvIdRoute
    }
    '/_authenticated/admin/support/$companyId': {
      id: '/_authenticated/admin/support/$companyId'
      path: '/$companyId'
      fullPath: '/admin/support/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminSupportCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAdminSupportRoute
    }
    '/_authenticated/admin/companies/$id': {
      id: '/_authenticated/admin/companies/$id'
      path: '/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCompaniesRoute
    }
    '/client/pv/$id/levee-reserves/$liftId': {
      id: '/client/pv/$id/levee-reserves/$liftId'
      path: '/levee-reserves/$liftId'
      fullPath: '/client/pv/$id/levee-reserves/$liftId'
      preLoaderRoute: typeof ClientPvIdLeveeReservesLiftIdRouteImport
      parentRoute: typeof ClientPvIdRoute
    }
  }
}

interface AuthenticatedParametresRouteChildren {
  AuthenticatedParametresApiRoute: typeof AuthenticatedParametresApiRoute
  AuthenticatedParametresAuditRoute: typeof AuthenticatedParametresAuditRoute
  AuthenticatedParametresBrandingRoute: typeof AuthenticatedParametresBrandingRoute
  AuthenticatedParametresDonneesRoute: typeof AuthenticatedParametresDonneesRoute
  AuthenticatedParametresIntegrationsRoute: typeof AuthenticatedParametresIntegrationsRoute
  AuthenticatedParametresNotificationsRoute: typeof AuthenticatedParametresNotificationsRoute
  AuthenticatedParametresNumerotationRoute: typeof AuthenticatedParametresNumerotationRoute
  AuthenticatedParametresPreferencesRoute: typeof AuthenticatedParametresPreferencesRoute
  AuthenticatedParametresSecuriteRoute: typeof AuthenticatedParametresSecuriteRoute
  AuthenticatedParametresIndexRoute: typeof AuthenticatedParametresIndexRoute
}

const AuthenticatedParametresRouteChildren: AuthenticatedParametresRouteChildren =
  {
    AuthenticatedParametresApiRoute: AuthenticatedParametresApiRoute,
    AuthenticatedParametresAuditRoute: AuthenticatedParametresAuditRoute,
    AuthenticatedParametresBrandingRoute: AuthenticatedParametresBrandingRoute,
    AuthenticatedParametresDonneesRoute: AuthenticatedParametresDonneesRoute,
    AuthenticatedParametresIntegrationsRoute:
      AuthenticatedParametresIntegrationsRoute,
    AuthenticatedParametresNotificationsRoute:
      AuthenticatedParametresNotificationsRoute,
    AuthenticatedParametresNumerotationRoute:
      AuthenticatedParametresNumerotationRoute,
    AuthenticatedParametresPreferencesRoute:
      AuthenticatedParametresPreferencesRoute,
    AuthenticatedParametresSecuriteRoute: AuthenticatedParametresSecuriteRoute,
    AuthenticatedParametresIndexRoute: AuthenticatedParametresIndexRoute,
  }

const AuthenticatedParametresRouteWithChildren =
  AuthenticatedParametresRoute._addFileChildren(
    AuthenticatedParametresRouteChildren,
  )

interface AuthenticatedTerrainRouteChildren {
  AuthenticatedTerrainIdRoute: typeof AuthenticatedTerrainIdRoute
}

const AuthenticatedTerrainRouteChildren: AuthenticatedTerrainRouteChildren = {
  AuthenticatedTerrainIdRoute: AuthenticatedTerrainIdRoute,
}

const AuthenticatedTerrainRouteWithChildren =
  AuthenticatedTerrainRoute._addFileChildren(AuthenticatedTerrainRouteChildren)

interface AuthenticatedAdminCompaniesRouteChildren {
  AuthenticatedAdminCompaniesIdRoute: typeof AuthenticatedAdminCompaniesIdRoute
}

const AuthenticatedAdminCompaniesRouteChildren: AuthenticatedAdminCompaniesRouteChildren =
  {
    AuthenticatedAdminCompaniesIdRoute: AuthenticatedAdminCompaniesIdRoute,
  }

const AuthenticatedAdminCompaniesRouteWithChildren =
  AuthenticatedAdminCompaniesRoute._addFileChildren(
    AuthenticatedAdminCompaniesRouteChildren,
  )

interface AuthenticatedAdminSupportRouteChildren {
  AuthenticatedAdminSupportCompanyIdRoute: typeof AuthenticatedAdminSupportCompanyIdRoute
  AuthenticatedAdminSupportIndexRoute: typeof AuthenticatedAdminSupportIndexRoute
}

const AuthenticatedAdminSupportRouteChildren: AuthenticatedAdminSupportRouteChildren =
  {
    AuthenticatedAdminSupportCompanyIdRoute:
      AuthenticatedAdminSupportCompanyIdRoute,
    AuthenticatedAdminSupportIndexRoute: AuthenticatedAdminSupportIndexRoute,
  }

const AuthenticatedAdminSupportRouteWithChildren =
  AuthenticatedAdminSupportRoute._addFileChildren(
    AuthenticatedAdminSupportRouteChildren,
  )

interface AuthenticatedPvIdRouteChildren {
  AuthenticatedPvIdHistoriqueRoute: typeof AuthenticatedPvIdHistoriqueRoute
  AuthenticatedPvIdLeveeReservesRoute: typeof AuthenticatedPvIdLeveeReservesRoute
}

const AuthenticatedPvIdRouteChildren: AuthenticatedPvIdRouteChildren = {
  AuthenticatedPvIdHistoriqueRoute: AuthenticatedPvIdHistoriqueRoute,
  AuthenticatedPvIdLeveeReservesRoute: AuthenticatedPvIdLeveeReservesRoute,
}

const AuthenticatedPvIdRouteWithChildren =
  AuthenticatedPvIdRoute._addFileChildren(AuthenticatedPvIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountSuspendedRoute: typeof AuthenticatedAccountSuspendedRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChantiersRoute: typeof AuthenticatedChantiersRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntrepriseRoute: typeof AuthenticatedEntrepriseRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRouteWithChildren
  AuthenticatedReservesRoute: typeof AuthenticatedReservesRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedTerrainRoute: typeof AuthenticatedTerrainRouteWithChildren
  AuthenticatedUpgradeRequiredRoute: typeof AuthenticatedUpgradeRequiredRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminLaunchChecklistRoute: typeof AuthenticatedAdminLaunchChecklistRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRouteWithChildren
  AuthenticatedPvIdRoute: typeof AuthenticatedPvIdRouteWithChildren
  AuthenticatedPvNewRoute: typeof AuthenticatedPvNewRoute
  AuthenticatedPvIndexRoute: typeof AuthenticatedPvIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountSuspendedRoute: AuthenticatedAccountSuspendedRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChantiersRoute: AuthenticatedChantiersRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntrepriseRoute: AuthenticatedEntrepriseRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRouteWithChildren,
  AuthenticatedReservesRoute: AuthenticatedReservesRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedTerrainRoute: AuthenticatedTerrainRouteWithChildren,
  AuthenticatedUpgradeRequiredRoute: AuthenticatedUpgradeRequiredRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminCompaniesRoute:
    AuthenticatedAdminCompaniesRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminLaunchChecklistRoute:
    AuthenticatedAdminLaunchChecklistRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRouteWithChildren,
  AuthenticatedPvIdRoute: AuthenticatedPvIdRouteWithChildren,
  AuthenticatedPvNewRoute: AuthenticatedPvNewRoute,
  AuthenticatedPvIndexRoute: AuthenticatedPvIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ClientPvIdRouteChildren {
  ClientPvIdLeveeReservesLiftIdRoute: typeof ClientPvIdLeveeReservesLiftIdRoute
}

const ClientPvIdRouteChildren: ClientPvIdRouteChildren = {
  ClientPvIdLeveeReservesLiftIdRoute: ClientPvIdLeveeReservesLiftIdRoute,
}

const ClientPvIdRouteWithChildren = ClientPvIdRoute._addFileChildren(
  ClientPvIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  LoginRoute: LoginRoute,
  MentionsRoute: MentionsRoute,
  SecuriteRoute: SecuriteRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  VerifyRoute: VerifyRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientHistoriqueRoute: ClientHistoriqueRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientProfilRoute: ClientProfilRoute,
  ClientVerifyRoute: ClientVerifyRoute,
  InviteTokenRoute: InviteTokenRoute,
  ClientPvIdRoute: ClientPvIdRouteWithChildren,
  SignPvTokenRoute: SignPvTokenRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicHooksCheckExpiringTrialsRoute:
    ApiPublicHooksCheckExpiringTrialsRoute,
  ApiPublicHooksDrainEmailsRoute: ApiPublicHooksDrainEmailsRoute,
  ApiPublicHooksDrainWebhooksRoute: ApiPublicHooksDrainWebhooksRoute,
  ApiPublicHooksHealthRoute: ApiPublicHooksHealthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
